pipeline:
  name: sam-pipeline
  identifier: sampipeline
  projectIdentifier: samproject
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: sam-stage
        identifier: samstage
        description: ""
        type: Deployment
        spec:
          deploymentType: AWS_SAM
          service:
            serviceRef: samservice
          environment:
            environmentRef: homolog
            deployToAll: false
            infrastructureDefinitions:
              - identifier: saminfra
          execution:
            steps:
              - stepGroup:
                  steps:
                    - step:
                        type: DownloadManifests
                        name: DownloadManifests
                        identifier: DownloadManifests
                        spec: {}
                        failureStrategies: []
                    - step:
                        type: AwsSamBuild
                        name: SAM Build
                        identifier: SAM_Build
                        spec:
                          connectorRef: account.harnessImage
                          image: harnessdev/sam-build:1.82.0-latest
                          imagePullPolicy: Always
                          buildCommandOptions:
                            - "--use-container"
                        when:
                          stageStatus: Success
                        failureStrategies: []
                    - step:
                        type: AwsSamDeploy
                        name: SAM Deploy
                        identifier: SAM_Deploy
                        spec:
                          connectorRef: account.harnessImage
                          image: harnessdev/sam-deploy:1.82.0-latest
                          imagePullPolicy: Always
                          stackName: sam-deploy
                          deployCommandOptions:
                            - "--parameter-overrides customLambdaRole=<+homolog.variables.LAMBDA_ROLE>"
                            - "--stack-name <+homolog.variables.STACK_NAME>"
                            - "--region <+homolog.variables.AWS_REGION>"
                            - "--capabilities CAPABILITY_IAM"
                            - "--s3-bucket <+homolog.variables.ARTIFACT_BUCKET>"
                            - "--no-fail-on-empty-changeset "
                            - "--on-failure DELETE"
                            - "--no-confirm-changeset"
                        when:
                          stageStatus: Success
                        timeout: 10m
                  name: SAM Step Group
                  identifier: sam_step_group
                  sharedPaths:
                    - /var/run
                    - /var/lib/docker
                  stepGroupInfra:
                    type: KubernetesDirect
                    spec:
                      connectorRef: <+input>
                      namespace: default
            rollbackSteps: []
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
