pipeline:
  name: sam-pipeline
  identifier: sampipeline
  projectIdentifier: samproject
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: build-setup
        identifier: buildsetup
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run Node setup
                  identifier: Run_Node_setup
                  spec:
                    connectorRef: account.harnessImage
                    image: node:20
                    shell: Bash
                    command: |-
                      node -v
                      npm --version
                      apt-get update && apt-get install -y zip
                      if [ -f src/handlers/package-lock.json ]; then
                        npm ci --prefix src/handlers
                      else
                        npm i --prefix src/handlers
                      fi
              - step:
                  type: Run
                  name: Snyk scan
                  identifier: Snyk_scan
                  spec:
                    connectorRef: account.harnessImage
                    image: node:20
                    shell: Sh
                    command: |-
                      cd src/handlers
                      npx snyk auth "$SNYK_TOKEN"
                      npx snyk test --severity-threshold=high
                      # npx snyk code test --severity-threshold=high
                      npx snyk monitor --project-name lambda-teste
                    envVariables:
                      SNYK_TOKEN: <+secrets.getValue("SNYK_TOKEN")>
              - step:
                  type: Run
                  name: S3Upload
                  identifier: S3Upload
                  spec:
                    connectorRef: account.harnessImage
                    image: docker.io/amazon/aws-cli:2.15.46
                    shell: Sh
                    command: |-
                      set -e

                      ( cd src/handlers && zip -r ../../build.zip . \
                          -x '*/__tests__/*' '*.test.*' '*/test/*' '*/__snapshots__/*' )
                      ls -lh build.zip

                      aws sts get-caller-identity
                      aws s3 ls "s3://${ARTIFACT_BUCKET}" >/dev/null
                      aws s3 cp build.zip "s3://${ARTIFACT_BUCKET}/${ARTIFACT_KEY}" --only-show-errors
                    envVariables:
                      ARTIFACT_KEY: app-lambda/build.zip
                      ARTIFACT_BUCKET: bucket-sam-teste
                      AWS_ACCESS_KEY_ID: <+secrets.getValue("AWS_access_key_ID")>
                      AWS_SECRET_ACCESS_KEY: <+secrets.getValue("AWS_secret_access_key")>
                      AWS_SESSION_TOKEN: <+secrets.getValue("AWS_session_token")>
    - stage:
        name: lambda-app
        identifier: lambdaapp
        description: ""
        type: Deployment
        spec:
          deploymentType: AwsLambda
          service:
            serviceRef: lambdateste
            serviceInputs:
              serviceDefinition:
                type: AwsLambda
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: <+input>
                      sources: <+input>
          environment:
            environmentRef: homolog
            deployToAll: false
            infrastructureDefinitions:
              - identifier: infralambda
          execution:
            steps:
              - step:
                  type: AwsLambdaDeploy
                  name: Deploy Lambda
                  identifier: Deploy_Lambda
                  spec: {}
                  timeout: 10m
                  failureStrategies:
                    - onFailure:
                        errors:
                          - AllErrors
                        action:
                          type: Ignore
                  strategy:
                    parallelism: 1
            rollbackSteps: []
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: Ignore
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: pad-directory-delete-data-main
        build: <+input>
