# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: SelfHosted

steps:
- checkout: self

- script: hostname
  displayName: 'Show hostname'

- script: echo "Agent hostname: $(hostname)"
  displayName: 'Echo hostname'
