name: Pipeline for pad-directory-delete-data deployment in HML
on:
  push:
    branches:
      - develop
  workflow_dispatch: # This event allows manual triggering

jobs:
  set-environment:
    environment: hml
    runs-on: ubuntu-latest
    outputs:
      LAMBDA_ROLE: ${{ vars.LAMBDA_ROLE }}
      BUCKET_NAME: ${{ vars.BUCKET_NAME }}
      STACK_NAME: ${{ vars.STACK_NAME }}
      ENV_VAR: ${{ vars.ENV_VAR }}
    steps:
      - name: Set variables based on the environment
        run: |
          echo "::set-output name=LAMBDA_ROLE::${{ vars.LAMBDA_ROLE }}"
          echo "::set-output name=BUCKET_NAME::${{ vars.BUCKET_NAME }}"
          echo "::set-output name=STACK_NAME::${{ vars.STACK_NAME }}"
          echo "::set-output name=ENV_VAR::${{ vars.ENV_VAR }}"
          
  code-deploy:    
    needs: set-environment
    uses: OpenBanking-Brasil/ofb-pipelines/.github/workflows/node-lambda-pipeline-hml.yml@main
    with:
      ENV_VAR: ${{ needs.set-environment.outputs.ENV_VAR }}
      LAMBDA_ROLE: ${{ needs.set-environment.outputs.LAMBDA_ROLE }}
      BUCKET_NAME: ${{ needs.set-environment.outputs.BUCKET_NAME }}
      STACK_NAME: ${{ needs.set-environment.outputs.STACK_NAME }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}   
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}   
      AWS_REGION: ${{ secrets.AWS_REGION }}
